unit = "mbit"
tc = "/sbin/tc"

[interfaces.nic]
dev = "eth0"

[hosts.lan]
ip = "192.168.2.0/24"

[speeds]
full = "30mbit"
almost = "25mbit"
slow = "5mbit"

[shaper.shaper]
dev = "nic"

[class.rootQ]
parent = "shaper"
rate = "full"
default = "base"

[shaper.makefair1]
parent = "base"
type = "sfq"
perturb = 10

[shaper.makefair2]
parent = "webserver"
type = "sfq"
perturb = 10

[class.base]
parent = "rootQ"
rate = "full"
ceil = "full"

[class.webserver]
parent = "rootQ"
rate = "100kbps"
ceil = "almost"
prio = 1

[match.filt1]
parent="shaper"
protocol = "ip"
prio = 2
sendTo = "webserver"
ip = {sport=80}

